// frontend/src/App.jsx
import { useEffect, useState } from 'react';
import { api, formatCents, toCents } from './api.js';
import CsvImport from './components/CsvImport.jsx';
import { ACCOUNT_TYPES, BANKS } from './lib/banks.js';

export default function App() {
  const [accounts, setAccounts] = useState([]);
  const [transactions, setTransactions] = useState([]);
  const [error, setError] = useState('');

  async function refresh() {
    try {
      const [a, t] = await Promise.all([api.getAccounts(), api.getTransactions()]);
      setAccounts(a);
      setTransactions(t);
      setError('');
    } catch (err) {
      setError(err.message);
    }
  }

  useEffect(() => {
    refresh();
  }, []);

  const totalCents = accounts.reduce((sum, a) => sum + a.balanceCents, 0);

  return (
    <main>
      <h1>Mes finances</h1>
      {error && <p className="error">{error}</p>}

      <section>
        <h2>Comptes — total {formatCents(totalCents)}</h2>
        <ul>
          {accounts.map((a) => (
            <li key={a._id} className="flex items-center gap-2">
              {BANKS[a.bank] && (
                <img src={BANKS[a.bank].logo} alt={BANKS[a.bank].name} className="size-5 rounded" />
              )}
              <strong>{a.name}</strong> ({ACCOUNT_TYPES[a.type] ?? a.type}) :{' '}
              {formatCents(a.balanceCents, a.currency)}
            </li>
          ))}
        </ul>
        <AccountForm onCreated={refresh} onError={setError} />
      </section>

      <CsvImport accounts={accounts} onImported={refresh} />

      <section>
        <h2>Transactions</h2>
        {accounts.length > 0 && (
          <TransactionForm accounts={accounts} onCreated={refresh} onError={setError} />
        )}
        <table>
          <thead>
            <tr>
              <th>Date</th>
              <th>Compte</th>
              <th>Description</th>
              <th>Montant</th>
              <th />
            </tr>
          </thead>
          <tbody>
            {transactions.map((t) => (
              <tr key={t._id}>
                <td>{new Date(t.date).toLocaleDateString('fr-CA')}</td>
                <td>{t.account?.name}</td>
                <td>{t.description}</td>
                <td className={t.amountCents < 0 ? 'negative' : 'positive'}>
                  {formatCents(t.amountCents)}
                </td>
                <td>
                  <button onClick={() => api.deleteTransaction(t._id).then(refresh)}>✕</button>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
    </main>
  );
}

function AccountForm({ onCreated, onError }) {
  const [name, setName] = useState('');
  const [type, setType] = useState('checking');
  const [initialBalance, setInitialBalance] = useState('0');

  async function submit(e) {
    e.preventDefault();
    try {
      await api.createAccount({ name, type, initialBalanceCents: toCents(initialBalance) });
      setName('');
      setInitialBalance('0');
      onCreated();
    } catch (err) {
      onError(err.message);
    }
  }

  return (
    <form onSubmit={submit}>
      <input placeholder="Nom du compte" value={name} onChange={(e) => setName(e.target.value)} required />
      <select value={type} onChange={(e) => setType(e.target.value)}>
        <option value="checking">Chèque</option>
        <option value="savings">Épargne</option>
        <option value="credit">Crédit</option>
        <option value="investment">Placement</option>
        <option value="cash">Comptant</option>
      </select>
      <input
        placeholder="Solde initial"
        value={initialBalance}
        onChange={(e) => setInitialBalance(e.target.value)}
      />
      <button type="submit">Ajouter le compte</button>
    </form>
  );
}

function TransactionForm({ accounts, onCreated, onError }) {
  const [account, setAccount] = useState(accounts[0]._id);
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [description, setDescription] = useState('');
  const [amount, setAmount] = useState('');

  async function submit(e) {
    e.preventDefault();
    try {
      await api.createTransaction({ account, date, description, amountCents: toCents(amount) });
      setDescription('');
      setAmount('');
      onCreated();
    } catch (err) {
      onError(err.message);
    }
  }

  return (
    <form onSubmit={submit}>
      <select value={account} onChange={(e) => setAccount(e.target.value)}>
        {accounts.map((a) => (
          <option key={a._id} value={a._id}>
            {a.name}
          </option>
        ))}
      </select>
      <input type="date" value={date} onChange={(e) => setDate(e.target.value)} required />
      <input
        placeholder="Description"
        value={description}
        onChange={(e) => setDescription(e.target.value)}
      />
      <input
        placeholder="Montant (négatif = dépense)"
        value={amount}
        onChange={(e) => setAmount(e.target.value)}
        required
      />
      <button type="submit">Ajouter</button>
    </form>
  );
}

// frontend/src/App.vue
<script setup lang="ts">
import type { Account, Category, Transaction } from '@/types';
import { computed, onMounted, ref } from 'vue';
import { api, formatCents } from '@/api';
import { BANKS } from '@/lib/banks';
import { ACCOUNT_TYPES } from '@/lib/labels';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Table,
  TableBody,
  TableEmpty,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table';
import AccountForm from './components/AccountForm.vue';
import CategoryManager from './components/CategoryManager.vue';
import CsvImport from './components/CsvImport.vue';
import TransactionForm from './components/TransactionForm.vue';
import TransactionRow from './components/TransactionRow.vue';

const accounts = ref<Account[]>([]);
const categories = ref<Category[]>([]);
const transactions = ref<Transaction[]>([]);
const error = ref('');

async function refresh() {
  try {
    const [a, c, t] = await Promise.all([
      api.getAccounts(),
      api.getCategories(),
      api.getTransactions(),
    ]);
    accounts.value = a;
    categories.value = c;
    transactions.value = t;
    error.value = '';
  } catch (err) {
    error.value = (err as Error).message;
  }
}

onMounted(refresh);

const totalCents = computed(() => accounts.value.reduce((sum, a) => sum + a.balanceCents, 0));

function setError(message: string) {
  error.value = message;
}
</script>

<template>
  <main class="mx-auto flex max-w-5xl flex-col gap-6 px-4 py-8">
    <h1 class="text-3xl font-semibold">Mes finances</h1>
    <p v-if="error" class="text-sm text-destructive">{{ error }}</p>

    <Card>
      <CardHeader>
        <CardTitle>Comptes — total {{ formatCents(totalCents) }}</CardTitle>
      </CardHeader>
      <CardContent class="flex flex-col gap-4">
        <ul class="flex flex-col gap-2">
          <li v-for="a in accounts" :key="a._id" class="flex items-center gap-2 text-sm">
            <img
              v-if="a.bank && BANKS[a.bank]"
              :src="BANKS[a.bank].logo"
              :alt="BANKS[a.bank].name"
              class="size-5 rounded"
            />
            <span class="font-medium">{{ a.name }}</span>
            <span class="text-muted-foreground">({{ ACCOUNT_TYPES[a.type] ?? a.type }})</span>
            <span class="ml-auto tabular-nums">{{ formatCents(a.balanceCents, a.currency) }}</span>
          </li>
        </ul>
        <AccountForm @created="refresh" @error="setError" />
      </CardContent>
    </Card>

    <CategoryManager :categories="categories" @changed="refresh" @error="setError" />

    <CsvImport :accounts="accounts" @imported="refresh" />

    <Card>
      <CardHeader>
        <CardTitle>Transactions</CardTitle>
      </CardHeader>
      <CardContent class="flex flex-col gap-4">
        <TransactionForm
          v-if="accounts.length > 0"
          :accounts="accounts"
          :categories="categories"
          @created="refresh"
          @error="setError"
        />
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Date</TableHead>
              <TableHead>Compte</TableHead>
              <TableHead>Description</TableHead>
              <TableHead>Catégorie</TableHead>
              <TableHead class="text-right">Montant</TableHead>
              <TableHead />
            </TableRow>
          </TableHeader>
          <TableBody>
            <TransactionRow
              v-for="t in transactions"
              :key="t._id"
              :transaction="t"
              :accounts="accounts"
              :categories="categories"
              @changed="refresh"
              @error="setError"
            />
            <TableEmpty v-if="transactions.length === 0" :colspan="6">Aucune transaction</TableEmpty>
          </TableBody>
        </Table>
      </CardContent>
    </Card>
  </main>
</template>
